export const COLORS = {
  primary: "#007DC2",
  secondary: "#373737",
  white: "#FFFFFF",
  black: "#000",
  themeBackground: "#fff",
  semiLightGrey: "#9A9A9A",
  lightGrey: "#DADADA",
  lightGray: "#606060",
  semiLightGray: "#EEEEEE",
  whiteSmoke: "#F9F9F9",
  gray: "#373737",
  borderPrimary: "#D9D9D9",
  red: "#E71F19",
  boldGrey: "#8D8D8D",
  selectColor: "#EBEBEB",
  inputBg: "#FAFAFA",
  grey: "#F5F5F5",
  borderSecondary: "#EBEBEB",
};
